version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/go/src/bulk-upload-poc
    restart: always
    ports:
      - '8080:8080'
    network_mode: host
  cache:
    image: redis/redis-stack
    container_name: app-cache-redis
    restart: always
    networks:
      - backend
    ports:
      - '6379:6379'
  database:
    image: mysql:5.7.39
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password --init-file=/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
volumes:
  db_data:
    driver: local

networks:
  backend:
