version: '3'

services:
  cache:
    image: redis/redis-stack
    container_name: app-cache-redis
    restart: always
    networks:
      - backend
    ports:
      - '6379:6379'
networks:
  backend:
